<br /><br />
<div id="view-content">
    <?php
//    echo "<h3>".$this->starNews->title."</h3>";
//    echo $this->starNews->body;

        if($this->newsList){
            echo "<ul class='listNews'>";
            echo $this->partialLoop("partials/row_pages.phtml", $this->newsList);
            echo "</ul>";
//            echo "<ul>";
//            foreach ($this->newsList as $key=>$value) {
//                echo "<li>".$value->title."</li>";
//            }
//            echo "<ul>";
        }
    ?>
</div>