<?php
echo $this->docType();
$this->layout()->userPanel = $this->action('panel','user');
?>

<html>
<head>
    <meta http-equiv="CONTENT-TYPE" content="text/html; charset=utf-8" />
    <link href="/skins/default/css/layout.css" rel="stylesheet" type="text/css" />
    <link href="/skins/default/css/style.css" rel="stylesheet" type="text/css" />
    <?php echo $this->headTitle();?>
    <script type="text/javascript" src="/js/jquery-2.1.3.js"></script>
</head>
<body>
<div id = "wrap">
    <?php
    echo $this->layout()->userPanel;
    echo $this->partial('header.phtml');
    ?>
    <div id = "main">
        <div id = "sidebar"></div>

        <div id = "breadcrumb">
            <?php echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(1)->render();?>
        </div>
        <div id = "content">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
    <?php echo $this->partial('footer.phtml');?>
</div>
</body>
</html>